services:
  minio:
    hostname: '${MINIO_HOSTNAME}'
    image: minio/minio
    container_name: minio
    restart: always
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - .storage/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
      # - "37335:37335"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio_key}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio_secret}
    command: server /data --console-address ":9001"
  mc:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      mc config host rm local;
      mc config host add --quiet --api s3v4 local http://$MINIO_HOSTNAME:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;
      mc rb --force local/kanastra/;
      mc mb --quiet local/kanastra/;
      mc cp /tmp/kanastra/* local/kanastra/raw/taxi/ --recursive;
      "
    
    env_file:
      - .env
    volumes:
      - /tmp:/tmp
    depends_on:
      - minio